### ISSUE TITLE
Power Tazer causes moster infighting.

### ISSUE THREAD

**Issue by JohnEdwa** [ThinkInvis/RoR2-Admiral#13]
Enemies zapped by the Power Tazer target the mob tazing them and start attacking it instead, but as there is no friendly-fire by default this is fruitless. While it does cause them to group up which is quite useful for nuking them with probes, they also don't stop attacking their friend unless attacked first ny another entity.

This can cause quite ridiculous display of a few dozen mobs circling each other attacking the thin air for the rest of the level, or if combined with the friendly fire Artifact, them simply killing each other for you.

[EDIT] This seems to be an issue with the base AI, because the succ pot item does the same thing, except it causes beetle guard allies to try attacking you. Not sure if it's worth trying to fix or just wait and see if Hopoo patches it out when they fix the succ pot item.

**Comment by ThinkInvis** [comment]
Fixed sometime in one of those recent messy refactor commits. Attacker is now registered as whoever inflicted the Shocked status to begin with, courtesy of a helper component.
