### ISSUE TITLE
special order beacon applies some items infinitely, especially void items

### ISSUE THREAD

**Issue by Littleevo** [ThinkInvis/RoR2-Admiral#23]
sometimes the special order beacon gives you the uncorrupted version of a void item. if you already have a void item, it will keep giving it to you infinitely. same thing happens with some modded items that upgrade, like mysticsitems' marwan's ash.

get a void item.
deploy special order beacon
wait for the beacon to give you the non-corrupted version of the item
see your stacks of that item go to infinity

Expected Behavior:
the beacon should give one stack of that void item, and take it away once you step away from the beacon.

Console Log:
[LogOutput.log](https://github.com/ThinkInvis/RoR2-Admiral/files/8212167/LogOutput.log)
i've closed the game a few seconds after the bug occurred. the beacon gave me about 590 needleticks.

**Comment by ThinkInvis** [comment]
Possible partial fix: ThinkInvis/TILER2@b935102e2e1b617071fabd9b0162edb10af77e7b (TILER2 v5.0.3). FakeInventory users may still incorrectly grant non-Void items, but should no longer allow them to be transformed. I can't test this at the moment due to not owning the expansion.

**Comment by Littleevo** [comment]
it works. thank you! if possible, please also add marwan's ash from mysticsitems, or maybe allow a config for that.
