### ISSUE TITLE
[suggestion] making orbital jump pad two-way.

### ISSUE THREAD

**Issue by Littleevo** [ThinkInvis/RoR2-Admiral#24]
orbital jump pad is a weird ability. its use is limited at best for normal runs, and it takes away one of ur best damage options for movement. it could shine in the simulacrum since venturing into the void is dangerous and you need to spend as little time there as possible, but because the jump pad is one-way, you'll need to walk back to the safe-zone, making that niche frustrating to deal with

my solution is making the construct two-way and making the jump pads land the player slightly in front of the destination pad, so you wouldn't get stuck traveling between the two. it would make the skill very useful in the simulacrum and make captain a great support.

another solution is having the jump-pad have 2 stocks and refresh 2 stocks at once, giving you more control over your movement. it could even help get around large gaps and corners.

**Comment by ThinkInvis** [comment]
Interception by terrain, enemies, etc. makes two-way jump pads difficult. Implemented 2-stock (which makes for slightly more interesting gameplay anyways) and some cooldown/range nerfs for balance in 0efebf600993bc23aad4a95c2ea0efb634e7b1fd, df0c24650eea2745f0ee7c5616f7072ebdcef1e5, d3ca0793871ac18a2300d76f5daadf5f893d104d.

**Comment by Littleevo** [comment]
thank you! i think captain might be the ultimate support in the simulacrum now!
