### ISSUE TITLE
Skill unlocks no longer functioning due to BepInExPack achievement changes

### ISSUE THREAD

**Issue by Jcat4609** [ThinkInvis/RoR2-Admiral#27]
### Describe the Bug
Achievements and skill unlocks don't unlock or function on the latest build of BepInExPack (5.4.1904) due to internal changes on achievement handling. 

### To Reproduce
1. Download Admiral mod and dependencies.
2. Use either profile with skills unlocked, or follow challenge requirements.
3. Note the skill continues to be locked, challenge progress isn't tracked, and no achievement pop-up appears.

### Expected Behavior
Skills should be unlocked, and an achievement should appear up the top of the screen to indicate that the challenge was completed.

### Console Log

[LogOutput.log](https://github.com/ThinkInvis/RoR2-Admiral/files/8538364/LogOutput.log)

### Additional Context
This does not only affect Admiral, but nearly every mod that adds custom achievements that are implemented in the old way. UnlockableAPI supposedly is still supported; but this isn't the case.

**Comment by ThinkInvis** [comment]
Fixed in c0b15ea608541acf3b238fdd3cafe190a5d66a3b.
