### ISSUE TITLE
Suggestion: Force Unlock option for skills

### ISSUE THREAD

**Issue by Moffein** [ThinkInvis/RoR2-Admiral#29]
It would be nice if there was a force unlock config option for the mod's skills. The "Kill 6 Enemies with Shock" achievement is impossible to complete if you don't use the mod's Shock changes, and the ability to unlock all skills from the get-go is useful when playing with randoms who don't normally use the mod (along with modded achievements sometimes getting reset due to bugs and game updates).

**Comment by ThinkInvis** [comment]
I consider this out of scope for all of my mods that have unlockables, as there are already at least two up-to-date mods solely dedicated to forcing unlocks. Either of these can be installed to provide this functionality to any other mod. See https://thunderstore.io/package/TheMysticSword/CheatUnlocks/ (individual) and https://thunderstore.io/package/XoXFaby/UnlockAll/ (all).
