### ISSUE TITLE
Orbital Probe Non-Functioning

### ISSUE THREAD

**Issue by imakunee** [ThinkInvis/RoR2-Admiral#6]
Version: 1.1.0

Pressing shift immediately puts the power on cooldown with no orbital strikes.

**Comment by ThinkInvis** [comment]
Can't reproduce. Please ensure that this bug is related to Admiral, i.e. that it does NOT happen after disabling/uninstalling Admiral without making any other changes to your modlist. If this is the case, I'll need a console log from a session of the game wherein the bug occurred.

**Comment by imakunee** [comment]
Sorry I found the issue. Forgot to do the basic step of install just the mod and check to see if it's a conflict, turns out it was another mod's fault. The author of the mod seems to have recently fixed the issue as well. Thank you for your patience!

For anyone who needs to know why they're having the same issue, in my case it was a slightly old version of RTAutoSprintEx causing Captain to sprint immediately after activating his Orbital Probe, which interrupts it. Ensure you're on the latest version if you're experiencing the same issue.
